version: '3'
services:
    web:
        build: .
        volumes: 
            - '.:/app'
            - '/app/node_modules'
            - '/app/package.json'
        ports: 
            - 3000:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true
